/* USRLIB MODULE INFORMATION

	MODULE NAME: simpleLogTst
	MODULE RETURN TYPE: int 
	NUMBER OF PARMS: 0
	ARGUMENTS:
	INCLUDES:
#include "keithley.h"
	END USRLIB MODULE INFORMATION
*/
int  simpleLogTst();
